### ISSUE TITLE
Cannot use the script

### ISSUE THREAD

**Issue by Rathanin-github** [ballesterus/Utensils#3]
Hi 
I am a bit new in bioinformatic and I am trying to use the script to concatenate my two multi-fasta alignment files (chr1.fasta and chr2.fasta). chr1.fasta is the alignment of 50 bacterial isolates of chromosome 1 and chr2.fasta is an alignment of 50 bacterial isolates of chr2 too. I ran : python geneStitcher.py -in chr1.fasta chr2.fasta 
I got an error message like this 
File "geneStitcher.py", line 47
    print 'Problem reading alignment: %s' % Alignment
                                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Problem reading alignment: %s' % Alignment)?
Could you please help to correct it or suggest a script to concatenate those two files?  I will be then you the concatenate file to construct the phylogenetic tree. 
Thanks in advance

**Comment by ZiliaMR** [comment]
I had the same problem, this is because this script is for python2. In another hand, @ballesterus Do you have new version for this script?. Thanks!

**Comment by ballesterus** [comment]
I apologize for the late response.  ZiliaMR is correct, the error is caused by a python version incompatibility. Despite the rise of python3 many clusters still use python2 as default. I have started python3 branch and updated geneStitcher.py and partBreaker.py Be sure to also switch to the python3 branch  of UPhO with

"git checkout python3_branch"

All the best

**Comment by ZiliaMR** [comment]
Nice! Is working!!!

(I didn't have the module "Get_fasta_from_Ref.py", but I was able to find it in your repositories).

Many thanks!



```
IMSSs-MacBook-Pro:Con imss$ python geneStitcher.py -in 1.fasta 2.fasta 
Done, goodbye
```
